### ISSUE TITLE
Failed login / 403 when the password contains some non-alphanumeric characters

### ISSUE THREAD

**Issue by vvaswani** [juliogonzalez/cp-installssl#5]
When using this script to install SSL, I always get a 403 Permission Denied error. Researching this further, I came across https://documentation.cpanel.net/display/DD/Guide+to+API+Authentication+-+Secure+Remote+Logins which requires remote logins to take place through the LogMeIn module. This script does not appear to log in using this route and this is possibly the reason for the 403.

**Comment by juliogonzalez** [comment]
Maybe not. Check if your password has non-alphanumeric characters. It seems the script I [borrowed and adapted](https://github.com/juliogonzalez/cp-installssl/blob/master/cp-installssl) fail in some cases, most probably when there are quotes, double quotes or whitespaces.

So my suggestion is to (temporary) switch to alphanumeric password and give it a try.

If you don't get the 403, that's the problem and:

1) This bug can be adapted (so I fix it soon)
2) You can workaround the problem by changing all values at the config file to be enclosed with double quotes (i.e. `host=”mydomain.com”`)

**Comment by vvaswani** [comment]
You're correct, my password included a special character. Using double quotes fixed it and allowed the login to proceed.

**Comment by vvaswani** [comment]
The next issue is that the SSL installation fails with an error message like `You must use an IP address that is on the server. “xxx.xxx.x.xxx” is not bound`. There are some possible solutions here: https://punchsalad.com/ssl-certificate/install-lets-encrypt-godaddy/#issue-use-IP-address. 

It could be because there is already an existing SSL certificate present on my domain but unfortunately as it is a production site, I cannot uninstall the existing certificate for testing purposes.

**Comment by juliogonzalez** [comment]
At least in my case (namecheap), I don't have problems having two certificates, and assigning the most recent one to the domain, so that is probably some kind of restriction or configuration at Godaddy.

But what you can do is creating a test subdomain for testing purposes. And when you verify that things are working, you can switch to the main domain.
